// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AboutFeatures } from "./AboutFeatures.js";

/**
 * Runtime introspection payload exposed by `GET /about`. Used by
 * the web "About" tab and the TUI's about view to render the
 * running daemon's identity + which optional features it was built
 * with. Sourced from `cfg!(feature = "...")` at daemon compile
 * time, so reflects the actual binary on disk rather than whatever
 * the wire client thinks should be enabled.
 */
export type AboutInfo = {
  /**
   * Crate version of `heimdall-core`. Matches the value baked
   * into other surfaces (`/health`, `/metrics`).
   */
  version: string;
  /**
   * Build profile of the daemon binary: `"debug"` or `"release"`.
   */
  build_profile: string;
  /**
   * Cargo feature flags compiled into the daemon. The set is
   * derived from `cfg!(feature = ...)` at build time.
   */
  features: AboutFeatures;
};
