// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-feature presence flags for [`AboutInfo`]. Each field maps
 * 1:1 to a Cargo feature in `crates/heimdall-daemon/Cargo.toml`;
 * `true` means the daemon binary was built with that feature on.
 */
export type AboutFeatures = {
  sqlite: boolean;
  aegis: boolean;
  river: boolean;
  fuzzer: boolean;
  cranelift: boolean;
};
