// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CampaignTemplate =
  | { kind: "bring-up" }
  | { kind: "characterization" }
  | { kind: "release" }
  | { kind: "custom"; name: string };
