// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CampaignState =
  | { state: "pending" }
  | { state: "running" }
  | { state: "pass" }
  | { state: "fail" }
  | { state: "mixed" }
  | { state: "cancelled" };
