// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One decoded instruction. `addr` is the architectural address the
 * instruction lives at (so the UI can highlight the line whose addr
 * matches the observed pc). `bytes` is the raw machine code in little-
 * endian order; useful for both render and bug-bounty triage. The
 * mnemonic and operands are pre-split so the UI can style them
 * independently (mnemonics bold, operands dim, register names with
 * the ABI overlay we already use for State rendering).
 */
export type DisasmLine = {
  addr: number;
  bytes: Array<number>;
  mnemonic: string;
  operands: string;
};
