// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisasmLine } from "./DisasmLine.js";
import type { Isa } from "./Isa.js";

/**
 * Structured output of [`crate::Disassembler::disassemble`]. `name`
 * is the disassembler identifier so the UI / API consumer can show
 * "decoded by llvm-objdump 21.1.8" or similar. `isa` is the ISA the
 * listing was decoded against, so a downstream consumer doesn't have
 * to thread DisasmOpts through to render.
 */
export type DisasmListing = {
  name: string;
  isa: Isa;
  lines: Array<DisasmLine>;
};
