// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which code generator a `JobKind::Fuzz` session uses. `RawAsm` is
 * the always-available hand-rolled RV64 encoder; `Cranelift` lowers
 * a randomised SSA IR through Cranelift's RV64 backend and only
 * works when the daemon was built with the `cranelift` cargo
 * feature (which transitively enables `heimdall-fuzzer/cranelift`).
 */
export type GeneratorKind = "raw-asm" | "cranelift";
