// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Instruction-set tag the disassembler needs to know about. RV64 today,
 * aarch64/x86 follow when other DUT families come online. Carrying ISA
 * in the opts (rather than inferring from artifact kind) keeps the
 * trait honest about the multi-ISA future and avoids surprise behavior
 * when a RawBytes blob is fed in without an ELF header to sniff.
 */
export type Isa = "rv64";
