// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratorKind } from "./GeneratorKind.js";

export type JobKind =
  | { kind: "mock-hello" }
  | {
      kind: "load-aegis-bitstream";
      descriptor_json: string;
      bitstream_b64: string;
    }
  | {
      kind: "run-aegis-vector";
      descriptor_json: string;
      bitstream_b64: string;
      inputs: { [key in string]: boolean };
      expected_outputs: { [key in string]: boolean };
      settle_cycles: number;
    }
  | { kind: "boot-river-elf"; elf_b64: string; cycles: number }
  | {
      kind: "fuzz";
      /**
       * Number of fuzz iterations to run.
       */
      iterations: number;
      /**
       * RNG seed. Deterministic with the same seed + generator config.
       */
      seed: number;
      /**
       * Instructions per generated program (for `RawAsmGen`-style
       * generators).
       */
      insn_count: number;
      /**
       * Per-iteration wait_halt budget in cycle-equivalents. Passed
       * straight to the driver via `Stimulus { budget: Cycles { count } }`.
       */
      cycles: number;
      /**
       * If true, a sim-vs-silicon coverage divergence flips the verdict
       * to fail. Off by default so fuzz runs keep going even when the
       * silicon and golden disagree on coverage.
       */
      strict_coverage: boolean;
      /**
       * Which code generator drives this fuzz session. Default
       * `raw-asm` keeps the proven hand-rolled RV64 encoder. The
       * `cranelift` choice requires the daemon (and heimdall-fuzzer)
       * to be built with the `cranelift` feature; the worker
       * surfaces a clean error otherwise.
       */
      generator: GeneratorKind;
    }
  | { kind: "named"; name: string; payload: unknown };
