// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerdictSummary } from "./VerdictSummary.js";

export type JobState =
  | { state: "queued" }
  | { state: "running" }
  | { state: "done"; detail: VerdictSummary }
  | { state: "failed"; detail: string }
  | { state: "cancelled" }
  | { state: "dead" };
