// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity tag on a `JobLog`. Matches the tracing convention. Serialized
 * as lowercase strings ("info", "warn", ...) for the WebSocket wire.
 */
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";
