// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-side tag mirroring `heimdall_test::SnapshotSource`. Lives here so
 * the `Event::DutStateSnapshot` variant has a Serialize/Deserialize-safe
 * kebab-case tag without the daemon needing a serde impl on the test
 * crate's enum.
 */
export type SnapshotSourceTag = "dut" | "golden";
