// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueRepr } from "./ValueRepr.js";

/**
 * A snapshot of architectural state. Ordered map so diffs are deterministic.
 */
export type State = {
  fields: { [key in string]: ValueRepr };
  captured_after: { secs: number; nanos: number } | null;
};
