// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed architectural-state value.
 */
export type ValueRepr =
  | { type: "u64"; value: number }
  | { type: "bytes"; value: Array<number> }
  | { type: "bool"; value: boolean };
