// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerdictSummary =
  | { kind: "pass" }
  | { kind: "fail"; reason: string }
  | { kind: "skip"; reason: string }
  | { kind: "error"; message: string };
